---
title: "Bad Markers"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#setwd("/projects/compsci/corneb_cs/workflowr/Thaiss/Thaiss_workflowr_2/")

#libraries
library(broman)
library(qtl2)
library(qtlcharts)
library(ggplot2)
library(ggrepel)
#library(DOQTL)
library(mclust)
#source("code/reconst_utils.R")
library("kableExtra")
library("knitr")
library("fst")
library(data.table) 
library(tidyr)     
library(mclust)     
library(rhdf5)      
library(optparse)
library(dplyr)
library(cluster)

```
```{r lsiting bad markers, echo=FALSE}

load("data/bad_markers_all.RData")
load("data/genotype_errors_marker.RData")
load("data/genotype_freq_marker.RData")
load("data/percent_missing_marker.RData")
gm <- get(load("data/gm_DO112_samqc.RData"))

#errors_mar <- colSums(e>2)/n_typed(gm, "marker")*100

#length(errors_mar[errors_mar > 5])

#bad_markers <- find_markerpos(gm, names(errors_mar[errors_mar > 5]))
#bad_markers$id <- rownames(bad_markers)

#error_mars_df <- as.data.frame(as.character(errors_mar[errors_mar > 5]))
#error_mars_df$id = names(errors_mar[errors_mar > 5])
#error_mars_df$index = 1: nrow(error_mars_df)

#bad_markers2 <- merge(bad_markers,error_mars_df, by=c("id"),all=T)
#names(bad_markers2)[5] <- c("error_mars")
#names(bad_markers2)[1] <- c("marker")
#bad_markers2 <- bad_markers2[order(bad_markers2$index),]

#rownames(bad_markers2) <- NULL

#Merging Data 

error_mars_df <- as.data.frame(errors_mar)
error_mars_df <- round(error_mars_df, digits = 4)
error_mars_df$marker = rownames(error_mars_df)

badmar_err <- merge(bad_markers,error_mars_df, by = "marker", all.x=T)

gf_mar_df <- as.data.frame(gf_mar)
gf_mar_df <- round(gf_mar_df, digits = 4)
gf_mar_df$marker = rownames(gf_mar_df)

badmar_err_gf <- merge(badmar_err,gf_mar_df, by = "marker", all.x=T)

pmis_mar_df <- as.data.frame(pmis_mar)
pmis_mar_df <- round(pmis_mar_df, digits = 4)
pmis_mar_df$marker = rownames(pmis_mar_df)

badmar_err_gf_pmis <- merge(badmar_err_gf,pmis_mar_df, by = "marker", all.x=T)

badmar_err_gf_pmis[is.na(badmar_err_gf_pmis)] <- '--'
names(badmar_err_gf_pmis)[6] <- c("AA_freq")
names(badmar_err_gf_pmis)[7] <- c("AB_freq")
names(badmar_err_gf_pmis)[8] <- c("BB_freq")


#find_markerpos(gm, 'complement121')

#gm_test <- drop_markers(gm_DO112_allqc, rownames(as.data.frame(gm$founder_geno)))

#complement121

badmar_err_gf_pmis <- badmar_err_gf_pmis[order(badmar_err_gf_pmis$chr, badmar_err_gf_pmis$gmap),]


badmar_err_gf_pmis[] %>%
   mutate(
     errors_mar = ifelse(errors_mar >= 5,
                  cell_spec(errors_mar, color = 'white',background = 'green'),
                  cell_spec(errors_mar, color = 'grey')),
     pmis_mar = ifelse(pmis_mar >= 10,
                  cell_spec(pmis_mar, color = 'white',background = 'red'),
                  cell_spec(pmis_mar, color = 'grey')),
     AA_freq = ifelse(AA_freq == 1,
                  cell_spec(AA_freq, color = 'white',background = 'blue'),
                  cell_spec(AA_freq, color = 'grey')),
     AB_freq = ifelse(AA_freq == 1,
                  cell_spec(AB_freq, color = 'white',background = 'blue'),
                  cell_spec(AB_freq, color = 'grey')),
     BB_freq = ifelse(AA_freq == 1,
                  cell_spec(BB_freq, color = 'white',background = 'blue'),
                  cell_spec(BB_freq, color = 'grey')),
     ) %>%
  kable(escape = F,align = c("ccccccccc"),linesep ="\\hline") %>%
  kable_styling(full_width = F) %>%
  kable_styling("striped", full_width = F)

```    