---
title: "Bad Markers"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#setwd("/projects/compsci/corneb_cs/workflowr/Thaiss/Thaiss_workflowr_2/")

#libraries
library(broman)
library(qtl2)
library(qtlcharts)
library(ggplot2)
library(ggrepel)
#library(DOQTL)
library(mclust)
#source("code/reconst_utils.R")
library("kableExtra")
library("knitr")
library("fst")
library(data.table) 
library(tidyr)     
library(mclust)     
library(rhdf5)      
library(optparse)
library(dplyr)
library(cluster)

```
```{r lsiting bad markers, echo=FALSE}

load("data/e_g_snpg_samqc.RData")
gm <- get(load("data/gm_DO112_samqc.RData"))

errors_mar <- colSums(e>2)/n_typed(gm, "marker")*100

#length(errors_mar[errors_mar > 5])

bad_markers <- find_markerpos(gm, names(errors_mar[errors_mar > 5]))
bad_markers$id <- rownames(bad_markers)

error_mars_df <- as.data.frame(as.character(errors_mar[errors_mar > 5]))
error_mars_df$id = names(errors_mar[errors_mar > 5])
error_mars_df$index = 1: nrow(error_mars_df)

bad_markers2 <- merge(bad_markers,error_mars_df, by=c("id"),all=T)
names(bad_markers2)[5] <- c("error_mars")
names(bad_markers2)[1] <- c("marker")
bad_markers2 <- bad_markers2[order(bad_markers2$index),]

rownames(bad_markers2) <- NULL

bad_markers2[1:5] %>%
  kable(escape = F,align = c("ccc"),linesep ="\\hline") %>%
  kable_styling(full_width = F) %>%
  kable_styling("striped", full_width = F)

```    