---
title: "Phenotype QC"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
output: html_document
---

This script is to investigate the distribution of the data. Types of distribution
* normal [no correction]
* positive skewness [possible correction: square root/logarithm]
* negative skewness [possible correction: reflect & square root/reflect & logarithm]
* positive kurtosis
* negative kurtosis 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)

filepathp = '/Users/corneb/Documents/MyJax/CS/Projects/qtl2/Univ_of_Penn_Thaiss/Thaiss/two.batches/data/'
pheno_file <- dir(path = filepathp, pattern = "Uni_of_Penn_Thaiss_pheno.3.csv", full.names = TRUE)
phenos <- read.csv(pheno_file)

phenos_cc <- subset(phenos, !is.na(Time_.min.))

library(Hmisc)
library(pastecs)
library(psych)

```

## Phenotype : Time
```{r plot sample distribution for Time}

time <- ggplot(data= phenos_cc, aes(x=phenos_cc$Time_.min.)) + 
geom_histogram(aes(y=..density..), fill="grey", color="white", position="identity") + 
geom_vline(xintercept=mean(phenos_cc$Time_.min.),size = 1, col="red") + 
labs(x="Time [mins]") + 
stat_function(fun = dnorm, color="blue", size=1, args=list(mean=mean(phenos_cc$Time_.min.), sd=sd(phenos_cc$Time_.min.))) 

time

Hmisc::describe(phenos$Time_.min.) 
pastecs::stat.desc(phenos$Time_.min.) 
psych::describe(phenos$Time_.min.) 

phenos_cc$trsfTime <- sqrt(max(phenos_cc$Time_.min.+1) - phenos_cc$Time_.min.)

trsfTime <- ggplot(data= phenos_cc, aes(x=phenos_cc$trsfTime)) + 
geom_histogram(aes(y=..density..), fill="grey", color="white", position="identity") + 
geom_vline(xintercept=mean(phenos_cc$trsfTime),size = 1, col="red") + 
labs(x="Time [mins]") + 
stat_function(fun = dnorm, color="blue", size=1, args=list(mean=mean(phenos_cc$trsfTime), sd=sd(phenos_cc$trsfTime))) 

trsfTime

#phenos$trsfTime <- sqrt(max(phenos$Time_.min.+1) - phenos$Time_.min.)

#Hmisc::describe(phenos$trsfTime)
Hmisc::describe(phenos_cc$trsfTime)  
#pastecs::stat.desc(phenos$trsfTime)
pastecs::stat.desc(phenos_cc$trsfTime) 
#psych::describe(phenos$trsfTime) 
psych::describe(phenos_cc$trsfTime) 

#Working out 3SD from mean
#phenos_cc$stdtime <- scale(phenos_cc$Time_.min.)
phenos_cc$stdtrsfTime <- scale(phenos_cc$trsfTime)

#phenos_cc$stdtimeo <- ifelse(phenos_cc$stdtime >= 3 | phenos_cc$stdtime <= -3, 'XX','')
phenos_cc$stdtrsfTimeo <- ifelse(phenos_cc$stdtrsfTime >= 3 | phenos_cc$stdtrsfTime <= -3, 'XX','')

table(phenos_cc$stdtrsfTimeo)

```

## Phenotype : Distance
```{r plot sample distribution for Distance}

distance <- ggplot(data= phenos_cc, aes(x=phenos_cc$Distance_.m.)) + 
geom_histogram(aes(y=..density..), fill="grey", color="white", position="identity") + 
geom_vline(xintercept=mean(phenos_cc$Distance_.m.),size = 1, col="red") + 
labs(x="Distance [m]") + 
stat_function(fun = dnorm, color="blue", size=1, args=list(mean=mean(phenos_cc$Distance_.m.), sd=sd(phenos_cc$Distance_.m.))) 

distance

Hmisc::describe(phenos$Distance_.m.) 
pastecs::stat.desc(phenos$Distance_.m.) 
psych::describe(phenos$Distance_.m.) 

#phenos_cc$refsqrtdistance <- sqrt(max(phenos_cc$Distance_.m.+1) - phenos_cc$Distance_.m.)

#refsqrtdistance <- ggplot(data= phenos_cc, aes(x=phenos_cc$refsqrtdistance)) + 
#geom_histogram(aes(y=..density..), fill="grey", color="white", position="identity") + 
#geom_vline(xintercept=mean(phenos_cc$refsqrtdistance),size = 1, col="red") + 
#labs(x="Distance [m]") + 
#stat_function(fun = dnorm, color="blue", size=1, args=list(mean=mean(phenos_cc$refsqrtdistance), sd=sd(phenos_cc$refsqrtdistance))) 

#refsqrtdistance

##Hmisc::describe(phenos$refsqrtdistance)
#Hmisc::describe(phenos_cc$refsqrtdistance)  
##pastecs::stat.desc(phenos$refsqrtdistance)
#pastecs::stat.desc(phenos_cc$refsqrtdistance) 
##psych::describe(phenos$refsqrtdistance) 
#psych::describe(phenos_cc$refsqrtdistance) 

#Working out 3SD from mean
phenos_cc$stddist <- scale(phenos_cc$Distance_.m.)

#phenos_cc$stdtimeo <- ifelse(phenos_cc$stdtime >= 3 | phenos_cc$stdtime <= -3, 'XX','')
phenos_cc$stddisto <- ifelse(phenos_cc$stddist  >= 3 | phenos_cc$stddist  <= -3, 'XX','')

table(phenos_cc$stddisto)

```

## Phenotype : Energy
```{r plot sample distribution for Energy}

energy <- ggplot(data= phenos_cc, aes(x=phenos_cc$Energy_.J.)) + 
geom_histogram(aes(y=..density..), fill="grey", color="white", position="identity") + 
geom_vline(xintercept=mean(phenos_cc$Energy_.J.),size = 1, col="red") + 
labs(x="Energy [J]") + 
stat_function(fun = dnorm, color="blue", size=1, args=list(mean=mean(phenos_cc$Energy_.J.), sd=sd(phenos_cc$Energy_.J.))) 

energy

Hmisc::describe(phenos$Energy_.J.) 
pastecs::stat.desc(phenos$Energy_.J.) 
psych::describe(phenos$Energy_.J.) 


#Working out 3SD from mean
phenos_cc$stden <- scale(phenos_cc$Energy_.J.)

#phenos_cc$stdtimeo <- ifelse(phenos_cc$stdtime >= 3 | phenos_cc$stdtime <= -3, 'XX','')
phenos_cc$stdeno <- ifelse(phenos_cc$stden  >= 3 | phenos_cc$stden  <= -3, 'XX','')

table(phenos_cc$stdeno)

```